name: game_defence
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flame: ^1.34.0
  flame_audio: ^2.11.12
  google_mobile_ads: ^5.3.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  mockito: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_test: ^1.17.1

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/characters/
    - assets/images/roads/
    - assets/temple/
    - assets/badges/elements/
    - assets/badges/ranks/
    - assets/config/
    - assets/data/
    - assets/images/characters/michael/
    - assets/images/characters/raphael/
    - assets/images/characters/uriel/
    - assets/images/characters/gabriel/
    - assets/images/characters/metatron/
    - assets/images/characters/seraphim/
    - assets/images/characters/lucifer/
    - assets/images/characters/asmodeus/
    - assets/images/characters/baal/
    - assets/images/characters/leviathan/
    - assets/images/characters/beelzebub/
    - assets/images/characters/abaddon/
    - assets/images/characters/enoch/
    - assets/images/characters/samael/
    - assets/images/characters/lilith/
    - assets/images/characters/azazel/
    - assets/images/characters/gaia/
    - assets/images/characters/apophis/
    - assets/badges/elements/
    - assets/badges/ranks/

  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf